- name: "Creates directory"
  file:
    path: "~/backend"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "artifact.tar.gz"
    dest: "~/backend/artifact.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/backend/artifact.tar.gz"
    dest: "~/backend"

- name: "Start the app"
  shell:
    cmd: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready