- name: "Creates directory"
  file:
    path: /home/ubuntu/web
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/web/artifact.tar.gz

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/web
    tar -xvf artifact.tar.gz

- name: "Start the app"
  shell:
    cmd: |
      cd /home/ubuntu/web
      npm install
      pm2 stop default
      pm2 start npm -- start